### ISSUE TITLE
Welcome email contains relative link on google signup (login link)

### ISSUE THREAD

**Issue by CloCkWeRX** [owntracks/hosted#10]
```

Thank you for signing up with us. <br/><br/>


	Your new account has been setup and you can now login using your Google credentials.<br/> 
        To login, visit <a href="/login/google">https://hosted.owntracks.org/login/google</a> <br/><br/>




```

**Comment by jpmens** [comment]
Thanks. (I have snipped your report above to protect your privacy. :-)

**Comment by binarybucks** [comment]
Thanks, fixed.

On Fri, Jun 19, 2015 at 10:04 AM, JP Mens <notifications@github.com> wrote:

> Thanks. (I have snipped your report above to protect your privacy. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/hosted/issues/10#issuecomment-113422655>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust
