### ISSUE TITLE
Failure to send email of newly generated credentials

### ISSUE THREAD

**Issue by CloCkWeRX** [owntracks/hosted#9]
https://hosted.owntracks.org/devices/149 -> Reset credentials -> Mail -> "A failure occured, please try again later".

I did however get the welcome email.

**Comment by jpmens** [comment]
I think you uncovered a bug. I see you registered with a username which includes your email address (this shouldn't have been possible ... :-)

Usernames *ought* to contain alphanumeric characters only.

**Comment by jpmens** [comment]
@CloCkWeRX Is there some way I can convince you to delete your account and try signing up again as you did? We've pushed a fix which should now forbid non-alphanumeric chars in username when signing up via Google/Facebook providers.

Sorry for the trouble!

**Comment by CloCkWeRX** [comment]
That seems to work, though gives the user a nasty login failed without an explanation of why.

Consider ```<input pattern="/[A-Za-z0-9]+/" title="An alphanumeric username you wish to be known by">```

**Comment by jpmens** [comment]
Thank you very much, @CloCkWeRX (for delete / re-signup)
We'll address this asap.

**Comment by binarybucks** [comment]
added HTML5 validation
